import { ePolygonNetwork, IAaveConfiguration } from "../../helpers/types";
import { AaveMarket } from "../aave/index";
import {
  strategyDAI,
  strategyUSDT,
  strategyWETH,
} from "../aave/reservesConfigs";
import { strategyBLSC } from "../archax/reservesConfigs";
import { ZERO_ADDRESS } from "../../helpers/constants";
import {
  strategyAGEUR,
  strategyBAL,
  strategyCRV,
  strategyDPI,
  strategyEURS,
  strategyGHST,
  strategyJEUR,
  strategyLINK,
  strategySUSHI,
  strategyWMATIC,
  strategyUSDC,
  strategyAAVE,
  strategyWBTC,
} from "./reservesConfigs";
// ----------------
// POOL--SPECIFIC PARAMS
// ----------------

export const ArchaxMarket: IAaveConfiguration = {
  ...AaveMarket,
  ProviderId: 34,
  WrappedNativeTokenSymbol: "WMATIC",
  MarketId: "Polygon Archax Market",
  ATokenNamePrefix: "Polygon",
  StableDebtTokenNamePrefix: "Polygon",
  VariableDebtTokenNamePrefix: "Polygon",
  SymbolPrefix: "Pol",
  ReservesConfig: {
    DAI: strategyDAI,
    LINK: strategyLINK,
    USDC: strategyUSDC,
    WBTC: strategyWBTC,
    WETH: strategyWETH,
    USDT: strategyUSDT,
    AAVE: strategyAAVE,
    WMATIC: strategyWMATIC,
    CRV: strategyCRV,
    SUSHI: strategySUSHI,
    GHST: strategyGHST,
    BAL: strategyBAL,
    DPI: strategyDPI,
    EURS: strategyEURS,
    JEUR: strategyJEUR,
    AGEUR: strategyAGEUR,
    BLSC: strategyBLSC,
  },
  ReserveAssets: {
    [ePolygonNetwork.polygon]: {
      AAVE: ZERO_ADDRESS,
      DAI: ZERO_ADDRESS,
      LINK: ZERO_ADDRESS,
      USDC: ZERO_ADDRESS,
      WBTC: ZERO_ADDRESS,
      WETH: ZERO_ADDRESS,
      USDT: ZERO_ADDRESS,
      WMATIC: ZERO_ADDRESS,
      GHST: ZERO_ADDRESS,
      BAL: ZERO_ADDRESS,
      CRV: ZERO_ADDRESS,
      DPI: ZERO_ADDRESS,
      SUSHI: ZERO_ADDRESS,
      EURS: ZERO_ADDRESS,
      JEUR: ZERO_ADDRESS,
      AGEUR: ZERO_ADDRESS,
      BLSC: "0x9971D0DA20Bb07dB4Db78f95174fbD839a7F5E4d",
    },
    [ePolygonNetwork.mumbai]: {
      AAVE: ZERO_ADDRESS,
      DAI: ZERO_ADDRESS,
      LINK: ZERO_ADDRESS,
      USDC: ZERO_ADDRESS,
      WBTC: ZERO_ADDRESS,
      WETH: ZERO_ADDRESS,
      USDT: ZERO_ADDRESS,
      WMATIC: ZERO_ADDRESS,
      GHST: ZERO_ADDRESS,
      BAL: ZERO_ADDRESS,
      CRV: ZERO_ADDRESS,
      DPI: ZERO_ADDRESS,
      SUSHI: ZERO_ADDRESS,
      EURS: ZERO_ADDRESS,
      JEUR: ZERO_ADDRESS,
      AGEUR: ZERO_ADDRESS,
      BLSC: "0x9971D0DA20Bb07dB4Db78f95174fbD839a7F5E4d",
    },
  },
  EModes: {
    StableEMode: {
      id: "1",
      ltv: "9700",
      liquidationThreshold: "9750",
      liquidationBonus: "10100",
      label: "Stablecoins",
      assets: ["USDC", "USDT", "DAI", "EURS", "JEUR", "AGEUR", "BLSC"],
    },
  },
  ChainlinkAggregator: {
    [ePolygonNetwork.polygon]: {
      AAVE: ZERO_ADDRESS,
      DAI: ZERO_ADDRESS,
      LINK: ZERO_ADDRESS,
      USDC: ZERO_ADDRESS,
      WBTC: ZERO_ADDRESS,
      WETH: ZERO_ADDRESS,
      USDT: ZERO_ADDRESS,
      WMATIC: ZERO_ADDRESS,
      GHST: ZERO_ADDRESS,
      BAL: ZERO_ADDRESS,
      CRV: ZERO_ADDRESS,
      DPI: ZERO_ADDRESS,
      SUSHI: ZERO_ADDRESS,
      // Using EUR / USD price feeds, not dedicated per EUR pegged tokens
      EURS: ZERO_ADDRESS,
      JEUR: ZERO_ADDRESS,
      AGEUR: ZERO_ADDRESS,
      BLSC: ZERO_ADDRESS,
    },
    [ePolygonNetwork.mumbai]: {
      AAVE: ZERO_ADDRESS,
      DAI: ZERO_ADDRESS,
      LINK: ZERO_ADDRESS,
      USDC: ZERO_ADDRESS,
      WBTC: ZERO_ADDRESS,
      WETH: ZERO_ADDRESS,
      USDT: ZERO_ADDRESS,
      WMATIC: ZERO_ADDRESS,
      GHST: ZERO_ADDRESS,
      BAL: ZERO_ADDRESS,
      CRV: ZERO_ADDRESS,
      DPI: ZERO_ADDRESS,
      SUSHI: ZERO_ADDRESS,
      // Using EUR / USD price feeds, not dedicated per EUR pegged tokens
      EURS: ZERO_ADDRESS,
      JEUR: ZERO_ADDRESS,
      AGEUR: ZERO_ADDRESS,
      BLSC: ZERO_ADDRESS,
    },
  },
};

export default ArchaxMarket;
